### ISSUE TITLE
constantly running 4 ghost members

### ISSUE THREAD

**Issue by mustafaiman** [hazelcast/hazelcast-member-tool#9]
`hazelcast-member` became unstable. Whatever command I try to run I get this error
```
Mustafas-MacBook-Pro:~ mustafaiman$ hazelcast-member status
ID                      PID     STATUS
Error            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/Error
occurred            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/occurred
during            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/during
initialization            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/initialization
of            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/of
VM            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/VM
java.lang.Error:            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/java.lang.Error:
Properties            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/Properties
init:            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/init:
Could            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/Could
not            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/not
determine            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/determine
current            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/current
working            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/working
directory.            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/directory.
at            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/at
java.lang.System.initProperties(Native            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/java.lang.System.initProperties(Native
Method)            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/Method)
at            Error: No PID file for Hazelcast member in /usr/local/var/run/hazelcast/at
java.lang.System.initializeSystemClass(System.java:1166)
```

If I try to start a member via `hazelcast-member start` it does start a member. When I try to stop it via `hazelcast-member stop`. It says
```
Error: Ambiguous command: 5 Hazelcast members
```
However `hazelcast-member list` shows only one member (the one I started with the tool) along with some error messages.
```
Mustafas-MacBook-Pro:~ mustafaiman$ hazelcast-member list
Error
occurred
during
initialization
of
VM
java.lang.Error:
Properties
init:
Could
not
determine
current
working
directory.
at
java.lang.System.initProperties(Native
Method)
at
java.lang.System.initializeSystemClass(System.java:1166)
blissful_hermann
```

I can stop `blissful_herman` with `hazelcast-member stop` but I cannot get rid of the remaining 4 members that `hazelcast-member` think they are running.

Mind that there is actually no hazelcast members running at this point (neither started from hazelcast-member nor explicitly from command line). I restarted the computer and did not run any members. I do not have any java processes running in activity monitor.

The only change I might have done between working and not working `hazelcast-member` is I installed iTerm2. This may or may not be related. After I start getting errors, I reinstalled hazelcast-member using 
```
$ brew uninstall hazelcast-member
$ brew untap hazelcast/homebrew-hazelcast
$ brew cleanup -s
$ brew tap hazelcast/homebrew-hazelcast
$ brew install hazelcast-member
```

However the errors are still there. I am using v3.11.

**Comment by googlielmo** [comment]
Quite strange, looks like a Java error was parsed into (unexisting) member names, which in turn leaves me wondering why Java cannot find the current directory.
Could you please `ls -al /usr/local/var/run/hazelcast/` to check whether it contains any leftover PID files?
If no member is running it should be empty.

**Comment by mustafaiman** [comment]
I resolved this issue by removing some files, breaking hazelcast-member completely and re-installing it a few days ago. I guess there were leftover files in that directory but I am not sure. I removed everything from probably that directory then I got this:

```
Mustafas-MacBook-Pro:target mustafaiman$ hazelcast-member start
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
mkdir: /usr/local/var/run/hazelcast/Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(Native Method)
	at java.lang.System.initializeSystemClass(System.java:1166): File exists
Error: Can't create temp directory
Mustafas-MacBook-Pro:target mustafaiman$ hazelcast-member status
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
ID                      PID     STATUS
reverent_moore          83109   Running
Mustafas-MacBook-Pro:target mustafaiman$ hazelcast-member stop
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Hazelcast instance reverent_moore with PID 83109 shut down
Mustafas-MacBook-Pro:target mustafaiman$ hazelcast-member status
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
ID                      PID     STATUS
```
I got these lines from my always active iterm terminal. It's been maybe 10 days after these. I re-installed hazelcast-member since then. I cannot reproduce it anymore.
